#!/bin/bash

# Check_mk plugin to check sidekiq queue length
#
#	Version 1.0
#
# 2013-07-03 demian@atpay.com
#	- First  version
#

QUEUE="default"

if which redis-cli && which sidekiq; then
	echo '<<<sidekiq>>>'
	echo 'qlen' `redis-cli llen $QUEUE`
fi
