#!/bin/bash

# Check_mk plugin to check sidekiq queue length
#
# 2013-07-23 demian@atpay.com
#	- version 2
#

LOWQUEUE="low"
CRITQUEUE="critical"
DEFQUEUE="default"
WORKERS="workers"

if which redis-cli && which redis-server; then
	echo '<<<sidekiq>>>'
	echo 'lowq' `redis-cli -n 12 LLEN $LOWQUEUE`
	echo 'critq' `redis-cli -n 12 LLEN $CRITQUEUE`
	echo 'defq' `redis-cli -n 12 LLEN $DEFQUEUE`
	echo 'workers' `redis-cli -n 12 SCARD $WORKERS`
fi
